Add project files
mohamedelshamy55/OOP-school-library pull request #1
Opened 2022-02-28 15:39 UTC by mohamedelshamy55

2022-02-28 16:28 UTC, eri8-9 requested changes
Hi @mohamedelshamy55 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

![almost there](https://media.giphy.com/media/7JsChhLbpj0rJtzimC/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-28 16:28 UTC, eri8-9 commented on person.rb
> +  def initialize(_id, age, name = 'unknown', parent_permission: true)
- [ ] it's not necessary to include "id" as a parameter. The id is part of the attributes and it's generated automatically.

2022-02-28 16:28 UTC, eri8-9 commented on student.rb
> +  end
- [ ] There is a typo in "_clasroom" should be "classroom" to match with the instance variable. You don't need to add the underscore sign in this case.

2022-02-28 16:28 UTC, eri8-9 commented on person.rb
> +  end
- [ ] It is a code style convention Method "can_use_service" should include "?" at the end as follow "can_use_service?" that way we are telling that method to return just true or false.
- [ ] "parent_permission" should be called as an instance variable as follow @parent_permission without "== true" if not the variable does not be called.

2022-02-28 16:28 UTC, er-contreras commented on person.rb
> +  end
- [ ] This method should be called as It is a code style convention to boolean values

2022-02-28 16:28 UTC, er-contreras commented on teacher.rb
> +  end
- [ ] After fixing the last reviews check in this class that you are able to create a teacher object to be sure that everything is working well. 😉

2022-02-28 18:17 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @mohamedelshamy55,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-01 13:14 UTC, mohamedelshamy55 commented
@TedLivist and @eri8-9 Thank you for finding time to review my project. I appreciate.

2022-03-01 13:14 UTC, merged