decorate a class
mohamedelshamy55/OOP-school-library pull request #2
Opened 2022-03-01 15:54 UTC by mohamedelshamy55

In this project, you will use the Decorator design pattern to validate and correct the names of people.
Implement composition (as an example of the design pattern).
Run a program using the command line.

2022-03-01 16:07 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @mohamedelshamy55,

Good job so far!
✔️ Implementation of Corrector instance in Person class
✔️ Implementation of `validate_name` method.
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
#### 🛑 🛑 Check this section as well 🛑 🛑
- [ ] **In your README, kindly add instructions on how to get your app locally**
- [ ] _Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-01 16:07 UTC, TedLivist commented on crorrector.rb
> +  end
- [ ] Your method does not return a capitalized string. Kindly fix that. You can resolve it by adding a bang sign (`!`) to the `capitalize` method.
- [ ] Your method is also supposed to return only 10 character string but it returns 11. Kindly fix this. `[0..9]` or `[0...10]` should work.

  ![elshamy-corr](https://user-images.githubusercontent.com/36542986/156204122-c350b2c6-08c2-47f2-8535-c428cffdb601.jpg)

2022-03-02 01:29 UTC, BrianSammit approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hello @mohamedelshamy55, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

TO HIGHLIGHT:

- Your project is professional 
- Your repo is professional 
- Well structured files 


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-02 14:10 UTC, mohamedelshamy55 commented on crorrector.rb
> +  end
thank you

2022-03-02 14:11 UTC, mohamedelshamy55 commented
@TedLivist @BrianSammit Thank you for finding time to review my project. I appreciate.

2022-03-02 14:11 UTC, merged